name: input call file
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: ''
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: print environment
      echo "print environment: ${{inputs.environment }}"
