name: linux commands
on:
  push:
    branches:
      - master
jobs:
  test:
    runs_on: windows_latest
    - name: print linux commands
      shell: bash
      run: |
      echo "this is test file"