name: Manual Input Workflow

on:
  push:
   branches:
    - master
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: checkout primary repository
        uses: actions/checkout@v4
      - name: checkout first repository
        uses: actions/checkout@v4
        with:
          repository: babu53/merge
          ref: refs/tags/T.V.1
          path: mergee   