name: 

on:
  # push:
  #  branches:
  #   - master
env:
  ACS.VersoinShort: 2025.1.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print build number
        run: |
          echo "Build Number: ${{ github.run_number }}"