name: Manual Input Workflow

on:
  push:
   branches:
    - master

env:
  GLOBAL_VAR: "global-value"

# jobs:
#   print-job:
#     runs-on: self-hosted
#     env:
#       JOB_VAR: "job-level"
#     steps:
#       - name: Step with env
#         shell: bash
#         env:
#           STEP_VAR: "step-value"
#         run: |
#           echo "Global var****: $GLOBAL_VAR"
#           echo "Job var: $JOB_VAR"
#           echo "Step var: $STEP_VAR"
jobs:
  linux-commands-on-windows:
    runs-on: self-hosted
    steps:
      - name: Run Linux commands using Git Bash
        #shell: bash
        run: |
          echo "This is Linux-style output"
          pwd
          ls -la