name: Manual Input Workflow

on:
  # push:
  #  branches:
  #   - master
  workflow_call:
   inputs:
     target-folder:
       required: true
       type: sting
       defalt: test

env:
  GLOBAL_VAR: "global-value"

jobs:
  print-job:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "job-level"
    steps:
      - name: Step with env
        shell: bash
        env:
          STEP_VAR: "step-value"
        run: |
          echo "Global var****: $GLOBAL_VAR"
          echo "Job var: $JOB_VAR"
          echo "Step var: $STEP_VAR"
          mkdir ${{inputs.target-folder}}