name: Manual Input Workflow

on:
  push:
   branches:
    - master

env:
  GLOBAL_VAR: "global-value"

jobs:
  print-job:
    runs-on: self-hosted
    env:
      JOB_VAR: "job-level"
    steps:
      - name: Step with env
        shell: pwsh
        env:
          STEP_VAR: "step-value"
        run: |
          echo "Global var****: $GLOBAL_VAR"
          echo "Job var: $JOB_VAR"
          echo "Step var: $STEP_VAR"
