name: Manual Input Workflow

on:
  push:
   branches:
    - master
jobs:
 test:
  runs-on: self-hosted
  steps:
    - name: run linux commands
      run: |
        echo "this is test file"
        echo "Today's date is $DATE"